name: code quality
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - tool_name: mypy
            run_command: mypy --install-types --non-interactive .
          - tool_name: ruff
            run_command: ruff check --no-fix .
          - tool_name: black
            run_command: black --check .

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install
        run: pip install -r requirements-dev.txt

      - name: Run ${{ matrix.tool_name }}
        run: ${{ matrix.run_command }}

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - pytest_job: py39
            python: "3.9"
            os_version: "ubuntu-latest"
          - pytest_job: py310
            python: "3.10"
            os_version: "ubuntu-latest"
          - pytest_job: py311
            python: "3.11"
            os_version: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 1

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - run: pip install -r requirements-dev.txt
      - run: cp .env.sample .env

      - name: Run ${{ matrix.pytest_job }} pytest job
        run: pytest
